/**
 * @fileoverview Optional adapter: nest-notification EmailService → nest-auth IEmailProvider.
 * @layer app/notification
 *
 * Maps each of the 7 nest-auth email-port methods to a canonical template and delegates
 * rendering, delivery, and audit logging to nest-notification's EmailService. The result:
 * one mailer, one template registry, and one delivery audit log — covering auth emails
 * alongside transactional ones.
 *
 * The tenant id is resolved from the current HTTP request's trusted `x-tenant-id` header
 * (the same convention used throughout the API), via NestJS REQUEST injection. This makes
 * the provider REQUEST-scoped — a new instance per request — keeping the tenant resolution
 * isolated without exposing `tenantId` as a parameter that the port interface does not include.
 *
 * @bymax-one/nest-auth is an illustrative peer — never a hard runtime dependency. The port
 * shape is mirrored locally in `auth-email.types.ts`.
 *
 * @module
 */
import { Inject, Injectable, Scope } from '@nestjs/common'
import { ConfigService } from '@nestjs/config'
import { REQUEST } from '@nestjs/core'
import type { Request } from 'express'
import { CANONICAL_EMAIL_TEMPLATES, EmailService } from '@bymax-one/nest-notification'

import { resolveTenantId } from '../common/tenant-id.decorator.js'
import type { Env } from '../config/env.schema.js'
import type { IEmailProvider, InviteData, SessionInfo } from './auth-email.types.js'

/** Application display name used in auth email bodies. */
const APP_NAME = 'Bymax'

/**
 * Adapts nest-notification's EmailService to the shape of @bymax-one/nest-auth's
 * IEmailProvider port.
 *
 * Each of the 7 port methods is mapped to a canonical template and delegated to
 * {@link EmailService.sendTemplate}, which handles rendering, HTML-escaping, masking,
 * and audit logging. Auth emails therefore flow through the same pipeline as all other
 * transactional sends — no second mailer, no second audit log.
 *
 * The provider is REQUEST-scoped so it can resolve the trusted tenant from the active
 * HTTP request's `x-tenant-id` header without exposing `tenantId` as a method parameter
 * (which the port interface does not include).
 *
 * Wire in the consuming module:
 * ```typescript
 * { provide: BYMAX_AUTH_EMAIL_PROVIDER, useClass: NotificationAuthEmailProvider }
 * ```
 */
@Injectable({ scope: Scope.REQUEST })
export class NotificationAuthEmailProvider implements IEmailProvider {
  constructor(
    private readonly email: EmailService,
    private readonly config: ConfigService<Env, true>,
    @Inject(REQUEST) private readonly request: Request,
  ) {}

  /** Resolve the trusted tenant id from the current request's `x-tenant-id` header. */
  private tenantId(): string {
    return resolveTenantId(this.request.headers['x-tenant-id'])
  }

  /**
   * Resolve the console base URL for action links from the Zod-validated config.
   *
   * Reads `WEB_ORIGIN` (defaulted to `http://localhost:3003` by the schema) through
   * ConfigService so the single source of truth for configuration is honoured rather
   * than reading `process.env` directly.
   */
  private baseUrl(): string {
    return this.config.get('WEB_ORIGIN', { infer: true })
  }

  /**
   * Send an email-verification OTP, mapping to the `otp_code` canonical template.
   *
   * The OTP is generated by nest-auth's own service and supplied here; this method
   * only renders, delivers, and audits — it never re-generates the code.
   *
   * @param to - Recipient email address.
   * @param otp - Short-lived OTP (never logged).
   * @param locale - BCP 47 locale tag; defaults to `'en'`.
   */
  async sendEmailVerificationOtp(to: string, otp: string, locale = 'en'): Promise<void> {
    await this.email.sendTemplate({
      tenantId: this.tenantId(),
      to,
      template: CANONICAL_EMAIL_TEMPLATES.OTP_CODE,
      locale,
      data: { code: otp, purpose: 'email_verification', appName: APP_NAME },
    })
  }

  /**
   * Send a password-reset OTP, mapping to the `otp_password_reset` canonical template.
   *
   * The OTP is generated by nest-auth; this method only renders, delivers, and audits it.
   *
   * @param to - Recipient email address.
   * @param otp - Short-lived OTP (never logged).
   * @param locale - BCP 47 locale tag; defaults to `'en'`.
   */
  async sendPasswordResetOtp(to: string, otp: string, locale = 'en'): Promise<void> {
    await this.email.sendTemplate({
      tenantId: this.tenantId(),
      to,
      template: CANONICAL_EMAIL_TEMPLATES.OTP_PASSWORD_RESET,
      locale,
      data: { code: otp, purpose: 'password_reset', appName: APP_NAME },
    })
  }

  /**
   * Send a password-reset link email, mapping to the `password_reset_link` template.
   *
   * The token is embedded in the reset URL only; it is never logged or returned standalone.
   *
   * @param to - Recipient email address.
   * @param token - Signed, opaque reset token (never logged).
   * @param locale - BCP 47 locale tag; defaults to `'en'`.
   */
  async sendPasswordResetToken(to: string, token: string, locale = 'en'): Promise<void> {
    const resetUrl = `${this.baseUrl()}/reset-password?token=${encodeURIComponent(token)}`
    await this.email.sendTemplate({
      tenantId: this.tenantId(),
      to,
      template: 'password_reset_link',
      locale,
      data: { resetUrl, appName: APP_NAME },
    })
  }

  /**
   * Send an MFA-enabled security notification, mapping to the `mfa_enabled` canonical template.
   *
   * @param to - Recipient email address.
   * @param locale - BCP 47 locale tag; defaults to `'en'`.
   */
  async sendMfaEnabledNotification(to: string, locale = 'en'): Promise<void> {
    await this.email.sendTemplate({
      tenantId: this.tenantId(),
      to,
      template: CANONICAL_EMAIL_TEMPLATES.MFA_ENABLED,
      locale,
      data: { appName: APP_NAME },
    })
  }

  /**
   * Send an MFA-disabled security notification, mapping to the `mfa_disabled` canonical template.
   *
   * @param to - Recipient email address.
   * @param locale - BCP 47 locale tag; defaults to `'en'`.
   */
  async sendMfaDisabledNotification(to: string, locale = 'en'): Promise<void> {
    await this.email.sendTemplate({
      tenantId: this.tenantId(),
      to,
      template: CANONICAL_EMAIL_TEMPLATES.MFA_DISABLED,
      locale,
      data: { appName: APP_NAME },
    })
  }

  /**
   * Send a new-session security alert, mapping to the `new_login_alert` canonical template.
   *
   * @param to - Recipient email address.
   * @param sessionInfo - Device description, IP address, and session hash.
   * @param locale - BCP 47 locale tag; defaults to `'en'`.
   */
  async sendNewSessionAlert(to: string, sessionInfo: SessionInfo, locale = 'en'): Promise<void> {
    await this.email.sendTemplate({
      tenantId: this.tenantId(),
      to,
      template: CANONICAL_EMAIL_TEMPLATES.NEW_LOGIN_ALERT,
      locale,
      data: {
        device: sessionInfo.device,
        ip: sessionInfo.ip,
        sessionHash: sessionInfo.sessionHash,
        appName: APP_NAME,
      },
    })
  }

  /**
   * Send a tenant invitation email, mapping to the `invitation` template.
   *
   * The invite token is embedded in the accept URL only; it is never logged or returned standalone.
   *
   * @param to - Recipient email address (the invitee).
   * @param inviteData - Invitation metadata (inviter, tenant, token, expiry).
   * @param locale - BCP 47 locale tag; defaults to `'en'`.
   */
  async sendInvitation(to: string, inviteData: InviteData, locale = 'en'): Promise<void> {
    const acceptUrl = `${this.baseUrl()}/accept-invite?token=${encodeURIComponent(inviteData.inviteToken)}`
    await this.email.sendTemplate({
      tenantId: this.tenantId(),
      to,
      template: 'invitation',
      locale,
      data: {
        inviterName: inviteData.inviterName,
        tenantName: inviteData.tenantName,
        acceptUrl,
        expiresAt: inviteData.expiresAt.toISOString(),
        appName: APP_NAME,
      },
    })
  }
}
